language: java
sudo: false

jdk:
  - openjdk11

script: ./travis.sh

env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "P8MWxZCrqcJIjiOKxiGQCWPNldHD28H+CyPHrsB9DhQ+RTRjD/Gxw9C5SmB9YQVhqD9VPus1/bllZhjZwBOgDQRVJu5oqS7QnJRtRammjKetN9/pZNaUbqDRV2QdgQhy58zBVOua5HN5jGKgA3PczXZY2pcpedAA/xbvCkS136w="
